# Generated by Django 4.2.23 on 2026-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityGrant',
            fields=[
                ('grant_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('action', models.CharField(choices=[('validate', 'Validate Vulnerability'), ('remediate', 'Coordinate Patch'), ('disclose', 'Prepare Disclosure'), ('publish', 'Publish Advisory')], max_length=20)),
                ('granted_by', models.EmailField(max_length=254)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'authority_grants',
            },
        ),
        migrations.CreateModel(
            name='AuthorityRevocation',
            fields=[
                ('revocation_id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20)),
                ('revoked_by', models.EmailField(max_length=254)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'authority_revocations',
            },
        ),
    ]
