# Generated by Django 4.2.23 on 2026-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authority', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoritygrant',
            name='agent_did',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='authoritygrant',
            name='t3n_proof',
            field=models.TextField(blank=True, default=''),
        ),
    ]
