# Generated by Django 4.2 on 2026-06-17 14:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityCase',
            fields=[
                ('case_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('severity_score', models.FloatField()),
                ('affected_systems', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
                ('researcher_email', models.EmailField(max_length=254)),
                ('researcher_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('validated', 'Validated'), ('remediated', 'Remediated'), ('disclosed', 'Disclosed'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('current_workflow_stage', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vulnerability_cases',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('recipient_address', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.vulnerabilitycase')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='AuthorityDelegation',
            fields=[
                ('delegation_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('authority_type', models.CharField(choices=[('investigation', 'Investigation'), ('remediation', 'Remediation'), ('disclosure', 'Disclosure'), ('publication', 'Publication')], max_length=20)),
                ('delegated_by', models.CharField(max_length=255)),
                ('delegated_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('terminal3_token', models.TextField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.vulnerabilitycase')),
            ],
            options={
                'db_table': 'authority_delegations',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_identity', models.CharField(max_length=255)),
                ('action_type', models.CharField(max_length=100)),
                ('authority_used', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.vulnerabilitycase')),
            ],
            options={
                'db_table': 'audit_log',
            },
        ),
    ]
